=== sshad0wtoxic/40260/xml/gramatica.dtd
<!ELEMENT entrenamiento (jugada+)>

<!ELEMENT jugada (nombre, (bucle | condicional | accion_simple)+)>
<!ELEMENT nombre (#PCDATA)>

<!ELEMENT bucle (repeticiones, accion_simple)>
<!ELEMENT repeticiones (#PCDATA)>

<!ELEMENT condicional (situacion, entonces, sino)>
<!ELEMENT situacion (#PCDATA)>
<!ELEMENT entonces (accion_simple)>
<!ELEMENT sino (accion_simple)>

<!ELEMENT accion_simple (saque?, recibir?, colocar?, rematar?)>

<!ELEMENT saque (tipo, zona)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT zona (#PCDATA)>

<!ELEMENT recibir (tecnica, precision)>
<!ELEMENT tecnica (#PCDATA)>
<!ELEMENT precision (#PCDATA)>

<!ELEMENT colocar (tiempo, zonaAtaque)>
<!ELEMENT tiempo (#PCDATA)>
<!ELEMENT zonaAtaque (#PCDATA)>

<!ELEMENT rematar (fuerza, direccion)>
<!ELEMENT fuerza (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>

=== sshad0wtoxic/40260/xml/gramatica.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entrenamiento SYSTEM "gramatica.dtd">

<entrenamiento>
    <jugada>
        <nombre>Estrategia de Contraataque</nombre>

        <condicional>
            <situacion>ataque_diagonal</situacion>
            <entonces>
                <accion_simple>
                    <recibir>
                        <tecnica>golpe_bajo</tecnica>
                        <precision>centro_red</precision>
                    </recibir>
                </accion_simple>
            </entonces>
            <sino>
                <accion_simple>
                    <rematar>
                        <fuerza>toque</fuerza>
                        <direccion>linea</direccion>
                    </rematar>
                </accion_simple>
            </sino>
        </condicional>

        <bucle>
            <repeticiones>10</repeticiones>
            <accion_simple>
                <saque>
                    <tipo>potencia</tipo>
                    <zona>1</zona>
                </saque>
            </accion_simple>
        </bucle>
    </jugada>
</entrenamiento>
